name: moodplaner
description: Discover new ways to listen to your music!
publish_to: 'none'
version: 0.0.8+5002

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  provider: ^5.0.0
  # For OS-specific directory paths
  path_provider: ^2.0.2
  assets_audio_player:
    git:
      url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
  flutter_media_metadata: ^0.1.0
  flutter_local_notifications: ^5.0.0
  file_picker: ^3.0.0
  permission_handler: ^6.1.1
  share: ^2.0.1
  palette_generator: ^0.3.0
  http: ^0.13.0
  path: ^1.8.0
  url_launcher: ^6.0.3
  implicitly_animated_reorderable_list: ^0.4.0-dev+4
  flag: ^5.0.0-nullsafety
  marquee: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^4.0.5955
  toggle_switch: ^1.2.0
  font_awesome_flutter: ^9.1.0
  flutter_riverpod: ^0.14.0+3
  intl: ^0.17.0
  dio: ^4.0.0
  flutter_slidable: ^0.6.0
  freezed: ^0.14.2
  loadmore: ^2.0.1
  easy_listview: ^0.1.3
  listview_utils: ^1.0.0-nullsafety
  lazy_loading_list: ^1.0.1
  kmodal_listview: ^0.0.2
  sqflite: ^2.0.0+3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  cryptography: ^2.0.2
  multi_select_flutter: ^4.0.0
  change_app_package_name: ^1.0.0
  flutter_secure_storage: ^4.2.1
  connectivity: ^3.0.6

dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/about-header.jpg
    - assets/images/collection-album.jpg
    - assets/images/credits-albums.jpg
    - assets/images/credits-tracks.jpg
    - assets/images/credits-artists.jpg
    - assets/images/credits-exception.jpg
    - assets/images/discover-albums.jpg
    - assets/images/discover-tracks.jpg
    - assets/images/discover-artists.jpg
    - assets/images/exception.jpg
    - assets/images/credits-album-art-0.jpg
    - assets/images/credits-album-art-1.jpg
    - assets/images/credits-album-art-2.jpg
    - assets/images/credits-album-art-3.jpg
